# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74bb0196b1a4729722470974362fd5c389538b0b305145c831b6c69dafb4e84ca3c1a5ae2bc1182c2652d9159926669f41a427f02454b198f8d4ff439b1c66f3

test:
  secret_key_base: ec9c88ca6c33dc74be10c17dcc4a19fd82460389340c096eb8992f05a4d37e5b9bf391cdf9ee0c6e937acef3384216c292a83fca20d1ba57df0a0b6b88dc9def

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
